import numpy as np
import pandas as pd
try:
    from . import config
except ImportError:
    import config

class HydraulicRam:
    def __init__(self, fluid_type: str = "Fresh Water", closure_factor: float = 1.0):
        self.fluid_type = fluid_type
        # Closure factor represents the speed of trapdoor closure.
        # 1.0 = Instantaneous (Full Joukowsky Shock)
        # < 1.0 = Slower closure (Reduced Shock)
        self.closure_factor = closure_factor
        
        if fluid_type == "Conductive Brine":
            self.density = 1050.0 # kg/m^3
            self.speed_of_sound = 1530.0 # m/s (approx for brine)
        else:
            self.density = 1000.0 # kg/m^3
            self.speed_of_sound = 1480.0 # m/s (Standard fresh water)

    def calculate_pressure_spike(self, flow_velocity: float) -> dict:
        """
        Calculates Water Hammer Pressure Spike using Joukowsky Equation.
        dP = rho * c * dV * ClosureFactor
        """
        delta_p_pascals = self.density * self.speed_of_sound * flow_velocity * self.closure_factor
        delta_p_bar = delta_p_pascals / 100000.0 # 1 Bar = 100,000 Pa
        
        return {
            "pressure_pa": delta_p_pascals,
            "pressure_bar": delta_p_bar,
            "fluid_density": self.density,
            "speed_of_sound": self.speed_of_sound
        }

    def simulate_hammer_curve(self, min_v: float = 0.0, max_v: float = 15.0) -> pd.DataFrame:
        """Simulates Pressure vs Velocity curve."""
        velocities = np.linspace(min_v, max_v, 100)
        pressures_bar = []
        
        for v in velocities:
            # Calculate P for this velocity
            p_pa = self.density * self.speed_of_sound * v * self.closure_factor
            pressures_bar.append(p_pa / 100000.0)
            
        return pd.DataFrame({
            'velocity_ms': velocities,
            'pressure_bar': pressures_bar
        })

class QuartziteReactor:
    def __init__(self, wall_thickness: float = 0.6):
        self.wall_thickness = wall_thickness
        self.g33_quartzite = 0.12 # Vm/N (Higher than granite due to 90% quartz content)

    def calculate_pulse_voltage(self, pressure_pa: float) -> float:
        """
        Calculates Voltage generated by the pressure pulse.
        V = g33 * Pressure * Thickness
        """
        voltage = self.g33_quartzite * pressure_pa * self.wall_thickness
        return voltage
        
    def simulate_voltage_curve(self, min_bar: float = 0, max_bar: float = 200) -> pd.DataFrame:
        """Simulates Voltage vs Pressure curve."""
        bars = np.linspace(min_bar, max_bar, 100)
        voltages = []
        
        for b in bars:
            pa = b * 100000.0
            v = self.calculate_pulse_voltage(pa)
            voltages.append(v)
            
        return pd.DataFrame({
            'pressure_bar': bars,
            'voltage_v': voltages
        })

