#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

HEADER = """# Daily index
#
# This file is generated by `daily/update_index.py`.

This index tracks daily folders stored in `daily/`.

## How to use

- Create a new folder for each day using `YYYY-MM-DD/`.
- Keep a short `README.md` inside each day folder with:
  - `# Daily - YYYY-MM-DD`
  - `Date: YYYY-MM-DD`
  - Optional `Summary:` line
- Run `python daily/update_index.py` to refresh this index (newest first).

## Entries (newest first)
"""


def read_summary(day_dir: Path) -> str:
    readme = day_dir / "README.md"
    if readme.exists():
        for line in readme.read_text(encoding="utf-8").splitlines():
            if line.startswith("Summary:"):
                summary = line.partition("Summary:")[2].strip()
                if summary:
                    return summary
    return f"Daily folder for {day_dir.name}."


def collect_day_dirs(daily_dir: Path) -> list[Path]:
    day_dirs = []
    for entry in daily_dir.iterdir():
        if entry.is_dir() and DATE_RE.match(entry.name):
            day_dirs.append(entry)
    return sorted(day_dirs, reverse=True)


def build_index(daily_dir: Path) -> str:
    lines = [HEADER.rstrip()]
    for day_dir in collect_day_dirs(daily_dir):
        summary = read_summary(day_dir)
        lines.append(
            f"- {day_dir.name} - [{day_dir.name}](./{day_dir.name}/) - {summary}"
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    daily_dir = Path(__file__).resolve().parent
    index_path = daily_dir / "index.md"
    index_path.write_text(build_index(daily_dir), encoding="utf-8")


if __name__ == "__main__":
    main()
